name: Other issue
description: Individual topic for TipTac Reborn
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the individual topic
      placeholder: Please describe.
    validations:
      required: true
