name: Bug report
description: Create a report to help improve TipTac Reborn
labels: 1_bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
